version: "3"
services:

  outline:
    image: outlinewiki/outline
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"

  storage:
    image: minio/minio
    env_file: ./docker.env
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'mkdir -p /opt/outline && /usr/bin/minio server /opt'
    environment:
      MINIO_ROOT_USER: AKda4c5923cfe6bce3fd13
      MINIO_ROOT_PASSWORD: SKec709281a53213d365a2aec392c05adf5b84bf85
      MINIO_REGION_NAME: self-hosted-1
    volumes:
      - ./opt:/data
    deploy:
      restart_policy:
        condition: on-failure

  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
    restart: always
